export const USER_ACTIONS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
};

export const COMMON_ACTIONS = {
  GET_DATA_REQUEST: 'GET_DATA_REQUEST',
  GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
  GET_DATA_FAILURE: 'GET_DATA_FAILURE',
  
  GET_DETAIL_DATA_REQUEST: 'GET_DETAIL_DATA_REQUEST',
  GET_DETAIL_DATA_SUCCESS: 'GET_DETAIL_DATA_SUCCESS',
  GET_DETAIL_DATA_FAILURE: 'GET_DETAIL_DATA_FAILURE',
  
  UPDATE_LOADER_REQUEST: 'UPDATE_LOADER_REQUEST',
  
  UPDATE_DATA_REQUEST: 'UPDATE_DATA_REQUEST'
};

export const DUMMY_ACTIONS = {
  GET_DUMMY_REQUEST: 'GET_DUMMY_REQUEST',
  GET_DUMMY_SUCCESS: 'GET_DUMMY_SUCCESS',
  GET_DUMMY_FAILURE: 'GET_DUMMY_FAILURE',
};
  