export const LANGUAGE = {
  EN: 1
};

export const LOCAL_STORAGE_KEYS = {
  ACCESS_TOKEN: 'GELV_MED_ACCESS_TOKEN',
  REFRESH_TOKEN: 'GELV_MED_REFRESH_TOKEN',
  USER_INFO: 'GELV_MED_USER_INFO',
};

export const LISTING_DATA = {
  FIRST_PAGE: 0,
  PAGE_SIZE: 40,
  PAGE_SIZE_INFO_BLOCK: 100,
  PAGE_SIZE_MAX_SIZE: 9999
};